In [2]:
from matplotlib.dates import DateFormatter, YearLocator
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import os
import pickle

In [3]:
df_merged = pd.read_csv("merged_task2.csv")

In [4]:
df_merged.head(10)

,display_id,num_comms,video_id,category,dislike_count,like_count,view_count,duration,upload_date
0,SBqSc91Hn9g,0.0,SBqSc91Hn9g,Film & Animation,1.0,8.0,1057.0,1159,2016-09-28 00:00:00
1,UuugEl86ESY,0.0,UuugEl86ESY,Film & Animation,1.0,23.0,12894.0,2681,2016-09-28 00:00:00
2,oB4c-yvnbjs,48.0,oB4c-yvnbjs,Film & Animation,779.0,1607.0,1800602.0,1394,2016-09-28 00:00:00
3,ZaV-gTCMV8E,6.0,ZaV-gTCMV8E,Film & Animation,24.0,227.0,57640.0,5064,2016-09-28 00:00:00
4,cGvL7AvMfM0,5.0,cGvL7AvMfM0,Film & Animation,13.0,105.0,86368.0,3554,2016-09-28 00:00:00
5,iVADSRjaLtQ,0.0,iVADSRjaLtQ,Film & Animation,1.0,11.0,3426.0,1066,2016-09-27 00:00:00
6,ypVcK9mldPc,0.0,ypVcK9mldPc,Film & Animation,2.0,11.0,7652.0,2450,2016-09-27 00:00:00
7,qA1NayP9cNY,0.0,qA1NayP9cNY,Film & Animation,0.0,9.0,479.0,1539,2016-09-27 00:00:00
8,CWdSl9ta4Rg,0.0,CWdSl9ta4Rg,Film & Animation,1.0,10.0,3856.0,2123,2016-09-27 00:00:00
9,64dCTkxCHpY,0.0,64dCTkxCHpY,Film & Animation,0.0,7.0,1730.0,1130,2016-09-27 00:00:00

In [5]:
df_merged["Engagement"] = (df_merged["num_comms"] + df_merged["like_count"] + df_merged["dislike_count"])/(df_merged["view_count"])

In [6]:
df_merged.head(10)

,display_id,num_comms,video_id,category,dislike_count,like_count,view_count,duration,upload_date,Engagement
0,SBqSc91Hn9g,0.0,SBqSc91Hn9g,Film & Animation,1.0,8.0,1057.0,1159,2016-09-28 00:00:00,0.008515
1,UuugEl86ESY,0.0,UuugEl86ESY,Film & Animation,1.0,23.0,12894.0,2681,2016-09-28 00:00:00,0.001861
2,oB4c-yvnbjs,48.0,oB4c-yvnbjs,Film & Animation,779.0,1607.0,1800602.0,1394,2016-09-28 00:00:00,0.001352
3,ZaV-gTCMV8E,6.0,ZaV-gTCMV8E,Film & Animation,24.0,227.0,57640.0,5064,2016-09-28 00:00:00,0.004459
4,cGvL7AvMfM0,5.0,cGvL7AvMfM0,Film & Animation,13.0,105.0,86368.0,3554,2016-09-28 00:00:00,0.001424
5,iVADSRjaLtQ,0.0,iVADSRjaLtQ,Film & Animation,1.0,11.0,3426.0,1066,2016-09-27 00:00:00,0.003503
6,ypVcK9mldPc,0.0,ypVcK9mldPc,Film & Animation,2.0,11.0,7652.0,2450,2016-09-27 00:00:00,0.001699
7,qA1NayP9cNY,0.0,qA1NayP9cNY,Film & Animation,0.0,9.0,479.0,1539,2016-09-27 00:00:00,0.018789
8,CWdSl9ta4Rg,0.0,CWdSl9ta4Rg,Film & Animation,1.0,10.0,3856.0,2123,2016-09-27 00:00:00,0.002853
9,64dCTkxCHpY,0.0,64dCTkxCHpY,Film & Animation,0.0,7.0,1730.0,1130,2016-09-27 00:00:00,0.004046

In [7]:
df_new = df_merged.drop(columns=['num_comms', 'like_count', 'video_id', 'dislike_count', 'like_count', 'upload_date', 'view_count', 'display_id'])

In [8]:
df_new.head(10)

           category  duration  Engagement
0  Film & Animation      1159    0.008515
1  Film & Animation      2681    0.001861
2  Film & Animation      1394    0.001352
3  Film & Animation      5064    0.004459
4  Film & Animation      3554    0.001424
5  Film & Animation      1066    0.003503
6  Film & Animation      2450    0.001699
7  Film & Animation      1539    0.018789
8  Film & Animation      2123    0.002853
9  Film & Animation      1130    0.004046

In [21]:
df_dummies_merged = pd.get_dummies(df_new, columns=['category'], drop_first=True)

In [31]:
df_dummies_merged = df_dummies_merged.sample(frac=1, random_state=42)

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm

In [33]:
df_dummies_merged.dropna(inplace = True)

In [46]:
df_LR = df_dummies_merged[:10000]

In [47]:
# Variables explicatives (features) et variable cible (target)
X = df_LR.drop(columns=["Engagement", "duration"])  # Toutes les colonnes sauf Engagement
y = df_LR["Engagement"]

# Ajout d'une constante (nécessaire pour l'interception dans statsmodels)
X = sm.add_constant(X)

# Modèle de régression linéaire
model = sm.OLS(y, X).fit()

# Résultats
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Engagement   R-squared:                       0.035
Model:                            OLS   Adj. R-squared:                  0.033
Method:                 Least Squares   F-statistic:                     25.62
Date:                Fri, 13 Dec 2024   Prob (F-statistic):           1.17e-66
Time:                        17:06:28   Log-Likelihood:                 17471.
No. Observations:               10000   AIC:                        -3.491e+04
Df Residuals:                    9985   BIC:                        -3.480e+04
Df Model:                          14
Covariance Type:            nonrobust
==================================================================================================
                                     coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------
const                              0.0180      0.002      7.499      0.000       0.013       0.023
category_Comedy                    0.0171      0.004      4.266      0.000       0.009       0.025
category_Education                 0.0087      0.003      2.868      0.004       0.003       0.015
category_Entertainment             0.0072      0.003      2.765      0.006       0.002       0.012
category_Film & Animation          0.0101      0.003      2.959      0.003       0.003       0.017
category_Gaming                    0.0202      0.003      7.827      0.000       0.015       0.025
category_Howto & Style             0.0228      0.003      7.557      0.000       0.017       0.029
category_Movies                 8.504e-18   3.05e-18      2.785      0.005    2.52e-18    1.45e-17
category_Music                     0.0078      0.003      2.877      0.004       0.002       0.013
category_News & Politics           0.0020      0.003      0.759      0.448      -0.003       0.007
category_Nonprofits & Activism     0.0008      0.005      0.166      0.868      -0.009       0.010
category_People & Blogs            0.0224      0.003      8.184      0.000       0.017       0.028
category_Pets & Animals            0.0088      0.005      1.687      0.092      -0.001       0.019
category_Science & Technology      0.0059      0.003      1.791      0.073      -0.001       0.012
category_Shows                 -1.228e-19    8.4e-20     -1.462      0.144   -2.87e-19    4.18e-20
category_Sports                   -0.0002      0.003     -0.052      0.958      -0.006       0.006
category_Travel & Events           0.0094      0.004      2.288      0.022       0.001       0.017
==============================================================================
Omnibus:                    18708.432   Durbin-Watson:                   1.971
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        107612451.625
Skew:                          13.613   Prob(JB):                         0.00
Kurtosis:                     510.473   Cond. No.                     1.46e+30
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.24e-57. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [37]:
X.head(25)

,const,duration,category_Comedy,category_Education,category_Entertainment,category_Film & Animation,category_Gaming,category_Howto & Style,category_Movies,category_Music,category_News & Politics,category_Nonprofits & Activism,category_People & Blogs,category_Pets & Animals,category_Science & Technology,category_Shows,category_Sports,category_Travel & Events
36669976,1.0,197,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
62671139,1.0,160,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
67210098,1.0,160,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
45134829,1.0,612,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
18157868,1.0,68,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
57716720,1.0,311,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
10723520,1.0,177,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
34543391,1.0,200,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
60003668,1.0,258,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
65572367,1.0,637,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
9971738,1.0,12545,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
62733860,1.0,103,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
41250598,1.0,28,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
478444,1.0,275,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
47870770,1.0,293,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
43967159,1.0,224,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
61484333,1.0,774,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
66817881,1.0,130,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
46673137,1.0,156,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
44974436,1.0,910,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
37128610,1.0,46,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
52626906,1.0,5684,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
52984999,1.0,83,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48221588,1.0,229,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
21798689,1.0,374,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [20]:
y.head(10)

0    0.008515
1    0.001861
2    0.001352
3    0.004459
4    0.001424
5    0.003503
6    0.001699
7    0.018789
8    0.002853
9    0.004046
Name: Engagement, dtype: float64

Ajouter un histogramme ou je vais mettre la moyenne de l'engagement en focntion de chaque catégorie